version: "3.7"
services:
  rtsp_proxy:
    build:
      context: rtsp
      dockerfile: Dockerfile
    ports:
      - "554:554"
    environment:
      CAMERA_IP: "${CAMERA_IP:?missing environment variable CAMERA_IP}"
  onvif_proxy:
    build:
      context: onvif
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      CAMERA_IP: "${CAMERA_IP:?missing environment variable CAMERA_IP}"
      RTSP_PROXY_HOST: "${RTSP_PROXY_HOST:?missing environment variable RTSP_PROXY_HOST}"
