version: "3.7"
services:
  rtsp_proxy:
    build:
      context: .
      dockerfile: Dockerfile-rtsp
    ports:
      - "554:554"
    environment:
      DESTINATION: "${CAMERA_IP:?missing environment variable CAMERA_IP}:554"
  onvif_proxy:
    build:
      context: .
      dockerfile: Dockerfile-onvif
    ports:
      - "8080:8080"
    environment:
      CAMERA_IP: "${CAMERA_IP:?missing environment variable CAMERA_IP}"
      ADVERTISED_PROXY_HOST: "${ADVERTISED_PROXY_HOST:?missing environment variable ADVERTISED_PROXY_HOST}"
